<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nails Glow</title>
    <link rel="stylesheet" href="./css/estilos.css">
</head>

<body>
    <!--menu navegación-->
    <header id="inicio">
        <nav class="menu">
            <div class="cajaLogo">
                <a href="../index.html"><img class="logo" src="./images/logo%20proyecto.png" alt="logo" width="500" height="144"></a>
            </div>
            <div class="lista-contenido">
                <ul class="lista">
                    <li><a href="#" class="activo">Índice</a></li>
                    <li><a href="./views/producto.html">Producto</a></li>
                    <li><a href="./views/presupuesto.html">Presupuesto</a></li>
                    <li><a href="./views/contacto.html">Contacto</a></li>
                </ul>
            </div>
        </nav>
        <!--banner-->
        <div class="banner">
            <div class="boton">
                <div>
                    <form action="./views/producto.html">    
                        <button type="button">Comprar</button>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <!--secciones-->
    <main>
        <div class="cajaSecciones">
            <section class="seccionUno">
                <div class="cajaTitulo">
                    <h2>Descubre nuestra colección</h2>
                </div>
                <div class="cajaProductos">
                    <div class="productoUno">
                        <div class="imagenProducto">
                            <img src="./images/coral.jpg" alt="esmaltecoral" width="1500" height="1500">
                        </div>
                        <div class="coral">
                            <h3>Esmalte permanente mini 5ml Coral Cove<br>#052</h3>
                        </div>
                        <div class="precio">
                            <span>4,99</span>
                            <span>€</span>
                        </div>
                        <div class="cajaPrecio">
                            <button class="botonPrecio">Añadir a la cesta</button>
                        </div>
                    </div>
                    <div class="productoUno">
                        <div class="imagenProducto">
                            <img src="./images/fuzzy.jpg" alt="esmaltefuzzy" width="1500" height="1500">
                        </div>
                        <div class="coral">
                            <h3>Esmalte permanente mini 5ml Fuzzy Peach <br>#052</h3>
                        </div>
                        <div class="precio">
                            <span>4.99</span>
                            <span>€</span>
                        </div>
                        <div class="cajaPrecio">
                            <button class="botonPrecio">Añadir a la cesta</button>
                        </div>
                    </div>
                    <div class="productoUno">
                        <div class="imagenProducto">
                            <img src="./images/dania.jpg" alt="esmaltedania" width="1500" height="1500">
                        </div>
                        <div class="coral">
                            <h3>Esmalte permanente mini 5ml Dania<br>#052</h3>
                        </div>
                        <div class="precio">
                            <span>4.99</span>
                            <span>€</span>
                        </div>
                        <div class="cajaPrecio">
                            <button class="botonPrecio">Añadir a la cesta</button>
                        </div>
                    </div>
                    <div class="productoUno">
                        <div class="imagenProducto">
                            <img src="./images/sweet.jpg" alt="esmaltesweet" width="1500" height="1500">
                        </div>
                        <div class="coral">
                            <h3>Esmalte permanente mini 5ml Sweet<br>#052</h3>
                        </div>
                        <div class="precio">
                            <span>4.99</span>
                            <span>€</span>
                        </div>
                        <div class="cajaPrecio">
                            <button class="botonPrecio">Añadir a la cesta</button>
                        </div>
                    </div>
                    <div class="productoUno">
                        <div class="imagenProducto">
                            <img src="./images/riviera.jpg" alt="esmalteriviera" width="1500" height="1500">
                        </div>
                        <div class="coral">
                            <h3>Esmalte permanente mini 5ml Riviera<br>#052</h3>
                        </div>
                        <div class="precio">
                            <span>4.99</span>
                            <span>€</span>
                        </div>
                        <div class="cajaPrecio">
                            <button class="botonPrecio">Añadir a la cesta</button>
                        </div>
                    </div>
                </div>
            </section>
            <section>
                <div class="articuloUno">
                    <div class="cajaTitulo">
                        <h2>Tu Destino para la Manicura Perfecta</h2>
                    </div>
                    <article class="cajaReportaje">
                        <div class="imagenReportaje">
                            <img src="./images/uniasrosa.jpg" alt="uñas rosa" width="736" height="1104">
                        </div>
                        <div class="textoReportaje">
                            <h3>¡Descubre la Magia de los Esmaltes de Uñas en Nuestra Tienda Online!</h3>
                            <p>Bienvenido a nuestro paraíso de colores, donde cada frasco contiene una dosis de magia y
                                estilo para tus uñas. <br>
                                Desde los tonos más clásicos y elegantes hasta los colores más atrevidos y vibrantes,
                                nuestra colección tiene algo para cada ocasión y estado de ánimo. <br> ¿Buscas un rojo
                                pasión
                                para una noche especial? ¿O tal vez un tono nude para una apariencia elegante en el trabajo?
                                No importa lo que estés buscando, lo tenemos cubierto.
                            </p>
                            <p>Nuestros esmaltes no solo destacan por su espectacular gama de colores, sino también por su
                                calidad excepcional. <br>Formulados con ingredientes de primera calidad, nuestros esmaltes
                                ofrecen una cobertura impecable, un brillo duradero y una aplicación suave y uniforme. <br>
                                Así que ¿qué estás esperando? Embellece tus uñas y haz una declaración de estilo con nuestra
                                increíble selección de esmaltes de uñas. <br>                            
                            </p>
                            <p class="destacado">¡Haz tu pedido hoy y deja que tus uñas sean la envidia de todos!</p>
                        </div>
                    </article>
                </div>
            </section>
            <section>
                <div class="articuloDos">
                    <div class="cajaTitulo">
                        <h2>El Secreto para unas Uñas Fuertes y Saludables</h2>
                    </div>
                    <article class="cajaNarracion">
                        <div class="narracion">
                            <h3>¡Uñas Bien Cuidadas!</h3>
                            <p>estamos dedicados a ofrecerte una selección premium de productos para el cuidado de uñas que
                                promueven la salud y la belleza de tus <br>
                                Desde fortalecedores hasta tratamientos hidratantes, nuestra colección está cuidadosamente
                                seleccionada para proporcionarte todo lo que necesitas <br>para mantener tus uñas en su
                                mejor
                                forma. Nuestros productos están formulados con ingredientes de alta calidad y diseñados para
                                abordar una variedad de necesidades, <br>ya sea que estés luchando contra las uñas
                                quebradizas,
                                las cutículas secas o la falta de brillo.
                            </p>
                            <p>Además de nuestros productos individuales, también ofrecemos kits de cuidado de uñas
                                completos que incluyen todo lo necesario para una rutina de cuidado completa.
                                Así que no esperes más. <br>Eleva tu rutina de cuidado de uñas a un nivel superior con nuestra
                                increíble selección de productos para el cuidado de uñas. <br>
                            </p>                       
                            <p class="destacado">¡Haz tu pedido hoy y descubre el secreto para unas uñas fuertes, saludables y hermosas!</p>
                        </div>
                        <div class="imagenNarracion">
                            <img src="./images/uniasnaranja.jpg" alt="uñas naranja" width="736" height="1104">                        
                        </div>
                    </article>
                </div>
            </section>
            <!--noticias-->
            <section>
                <div class="cajaNoticia">
                    <div class="cajaTitulo">
                        <h2>Noticias</h2>
                    </div>
                    <div>
                       <div id="nuevoContenido">
                        
                       </div>
                    </div>
                </div>
            </section>
        </div>
    </main>
       
   
    <!--pie de pagina-->
    <footer>
        <div class="cajaFooter">
            <div class="cajaAtencion">
                <h4>ATENCIÓN AL CLIENTE</h4>
                <p>Av. Severo Ochoa 27</p>
                <p>Teléfono: (+34) 617255191</p> 
                <p>Email: tienda@nailglow</p>                     
            </div>
            <div class="cajaAviso">
                <h4>INFORMACIÓN LEGAL</h4>
                <P>Aviso legal</P>
            </div>
            <div class="cajaRedes">
                <h4>SIGUENOS</h4>
                <div class="logoRedes">
                    <a href="https://www.instagram.com/">
                        <img src="./images/instagram.png" alt="logo instagram" width="60" height="60">
                    </a>
                    <a href="https://www.facebook.com/">
                        <img src="./images/facebook.png" alt="logo facebook" width="60" height="60">
                    </a>
                    <a href="https://www.pinterest.es/">
                        <img src="./images/pinterest.png" alt="logo pinteres" width="60" height="60">
                    </a>
                    <a href="https://www.youtube.com/">
                        <img src="./images/youtube.png" alt="logo youtube" width="60" height="60">  
                    </a>
                </div>
            </div>

        </div>
    </footer>

    <!--enlace a js-->
    <script src="./js/script.js"></script>
</body>

</html>
